version: '3'
services:
  app:
    container_name: bobross_paint
    build: ./app
    ports:
      - "8500:8500"
    volumes:
      - ./app:/usr/src/app

  api:
    container_name: api
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/api